version: "2"
services:
  db:
    container_name: postgres
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=localhost
    ports:
      - "5999:5432"
